-- Convert pairs and settings

INSERT INTO platform_settings (`name`, `value`) VALUES ('convert_fee_bps','50'), ('convert_min_usdt','10') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

CREATE TABLE IF NOT EXISTS convert_pairs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  category ENUM('gold','stocks','crypto') NOT NULL,
  symbol VARCHAR(32) NOT NULL,
  base_asset VARCHAR(16) NOT NULL,
  quote_asset VARCHAR(16) NOT NULL,
  token_symbol VARCHAR(32) NOT NULL,
  display_name VARCHAR(80) NOT NULL,
  logo_url VARCHAR(512) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_convert_pairs_category_symbol (category, symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO convert_pairs (category, symbol, base_asset, quote_asset, token_symbol, display_name, logo_url, sort_order, active) VALUES
('gold','XAUT/USDT','XAUT','USDT','XAUT','Tether Gold','https://api.dicebear.com/9.x/shapes/png?seed=XAUT',1,1),
('stocks','NVDAON/USDT','NVDAON','USDT','NVDA','NVDA','https://api.dicebear.com/9.x/shapes/png?seed=NVDA',2,1),
('stocks','TSLAON/USDT','TSLAON','USDT','TSLA','TSLA','https://api.dicebear.com/9.x/shapes/png?seed=TSLA',3,1),
('stocks','TSMON/USDT','TSMON','USDT','TSM','TSM','https://api.dicebear.com/9.x/shapes/png?seed=TSM',4,1),
('stocks','AAPLON/USDT','AAPLON','USDT','AAPL','AAPL','https://api.dicebear.com/9.x/shapes/png?seed=AAPL',5,1),
('stocks','GOOGLON/USDT','GOOGLON','USDT','GOOGL','GOOGL','https://api.dicebear.com/9.x/shapes/png?seed=GOOGL',6,1),
('stocks','AMZNON/USDT','AMZNON','USDT','AMZN','AMZN','https://api.dicebear.com/9.x/shapes/png?seed=AMZN',7,1),
('stocks','BABAON/USDT','BABAON','USDT','BABA','BABA','https://api.dicebear.com/9.x/shapes/png?seed=BABA',8,1),
('stocks','GSON/USDT','GSON','USDT','GS','GS','https://api.dicebear.com/9.x/shapes/png?seed=GS',9,1),
('stocks','TON/USDT','TON','USDT','T','T','https://api.dicebear.com/9.x/shapes/png?seed=T',10,1),
('stocks','UBERON/USDT','UBERON','USDT','UBER','UBER','https://api.dicebear.com/9.x/shapes/png?seed=UBER',11,1),
('stocks','FON/USDT','FON','USDT','F','F','https://api.dicebear.com/9.x/shapes/png?seed=F',12,1),
('stocks','TMON/USDT','TMON','USDT','TM','TM','https://api.dicebear.com/9.x/shapes/png?seed=TM',13,1),
('stocks','WMTON/USDT','WMTON','USDT','WMT','WMT','https://api.dicebear.com/9.x/shapes/png?seed=WMT',14,1),
('stocks','VZON/USDT','VZON','USDT','VZ','VZ','https://api.dicebear.com/9.x/shapes/png?seed=VZ',15,1),
('stocks','BLKON/USDT','BLKON','USDT','BLK','BLK','https://api.dicebear.com/9.x/shapes/png?seed=BLK',16,1),
('stocks','INTCON/USDT','INTCON','USDT','INTC','INTC','https://api.dicebear.com/9.x/shapes/png?seed=INTC',17,1),
('stocks','IBMON/USDT','IBMON','USDT','IBM','IBM','https://api.dicebear.com/9.x/shapes/png?seed=IBM',18,1),
('stocks','AMDON/USDT','AMDON','USDT','AMD','AMD','https://api.dicebear.com/9.x/shapes/png?seed=AMD',19,1),
('stocks','METAON/USDT','METAON','USDT','META','META','https://api.dicebear.com/9.x/shapes/png?seed=META',20,1),
('stocks','MSFTON/USDT','MSFTON','USDT','MSFT','MSFT','https://api.dicebear.com/9.x/shapes/png?seed=MSFT',21,1),
('stocks','ORCLON/USDT','ORCLON','USDT','ORCL','ORCL','https://api.dicebear.com/9.x/shapes/png?seed=ORCL',22,1),
('stocks','SNDKON/USDT','SNDKON','USDT','SNDK','SNDK','https://api.dicebear.com/9.x/shapes/png?seed=SNDK',23,1),
('stocks','PFEON/USDT','PFEON','USDT','PFE','PFE','https://api.dicebear.com/9.x/shapes/png?seed=PFE',24,1),
('stocks','PGON/USDT','PGON','USDT','PG','PG','https://api.dicebear.com/9.x/shapes/png?seed=PG',25,1),
('stocks','KOON/USDT','KOON','USDT','KO','KO','https://api.dicebear.com/9.x/shapes/png?seed=KO',26,1),
('stocks','MCDON/USDT','MCDON','USDT','MCD','MCD','https://api.dicebear.com/9.x/shapes/png?seed=MCD',27,1),
('stocks','SBUXON/USDT','SBUXON','USDT','SBUX','SBUX','https://api.dicebear.com/9.x/shapes/png?seed=SBUX',28,1),
('stocks','PEPON/USDT','PEPON','USDT','PEP','PEP','https://api.dicebear.com/9.x/shapes/png?seed=PEP',29,1),
('stocks','PCGON/USDT','PCGON','USDT','PCG','PCG','https://api.dicebear.com/9.x/shapes/png?seed=PCG',30,1),
('stocks','PINSON/USDT','PINSON','USDT','PINS','PINS','https://api.dicebear.com/9.x/shapes/png?seed=PINS',31,1),
('stocks','PYPLON/USDT','PYPLON','USDT','PYPL','PYPL','https://api.dicebear.com/9.x/shapes/png?seed=PYPL',32,1),
('stocks','QCOMON/USDT','QCOMON','USDT','QCOM','QCOM','https://api.dicebear.com/9.x/shapes/png?seed=QCOM',33,1),
('stocks','RDDTON/USDT','RDDTON','USDT','RDDT','RDDT','https://api.dicebear.com/9.x/shapes/png?seed=RDDT',34,1),
('stocks','SMCION/USDT','SMCION','USDT','SMCI','SMCI','https://api.dicebear.com/9.x/shapes/png?seed=SMCI',35,1),
('stocks','SNAPON/USDT','SNAPON','USDT','SNAP','SNAP','https://api.dicebear.com/9.x/shapes/png?seed=SNAP',36,1),
('stocks','SNOWON/USDT','SNOWON','USDT','SNOW','SNOW','https://api.dicebear.com/9.x/shapes/png?seed=SNOW',37,1),
('stocks','SPOTON/USDT','SPOTON','USDT','SPOT','SPOT','https://api.dicebear.com/9.x/shapes/png?seed=SPOT',38,1),
('stocks','VON/USDT','VON','USDT','V','V','https://api.dicebear.com/9.x/shapes/png?seed=V',39,1),
('stocks','MAON/USDT','MAON','USDT','MA','MA','https://api.dicebear.com/9.x/shapes/png?seed=MA',40,1),
('stocks','JNJON/USDT','JNJON','USDT','JNJ','JNJ','https://api.dicebear.com/9.x/shapes/png?seed=JNJ',41,1),
('stocks','JPMON/USDT','JPMON','USDT','JPM','JPM','https://api.dicebear.com/9.x/shapes/png?seed=JPM',42,1),
('stocks','MSTRON/USDT','MSTRON','USDT','MSTR','MSTR','https://api.dicebear.com/9.x/shapes/png?seed=MSTR',43,1),
('stocks','NFLXON/USDT','NFLXON','USDT','NFLX','NFLX','https://api.dicebear.com/9.x/shapes/png?seed=NFLX',44,1),
('stocks','NKEON/USDT','NKEON','USDT','NKE','NKE','https://api.dicebear.com/9.x/shapes/png?seed=NKE',45,1),
('stocks','NVOON/USDT','NVOON','USDT','NVO','NVO','https://api.dicebear.com/9.x/shapes/png?seed=NVO',46,1),
('stocks','ONON/USDT','ONON','USDT','ON','ON','https://api.dicebear.com/9.x/shapes/png?seed=ON',47,1),
('stocks','XOMON/USDT','XOMON','USDT','XOM','XOM','https://api.dicebear.com/9.x/shapes/png?seed=XOM',48,1),
('stocks','USOON/USDT','USOON','USDT','USO','USO','https://api.dicebear.com/9.x/shapes/png?seed=USO',49,1),
('stocks','ABNBON/USDT','ABNBON','USDT','ABNB','ABNB','https://api.dicebear.com/9.x/shapes/png?seed=ABNB',50,1),
('stocks','HOODON/USDT','HOODON','USDT','HOOD','HOOD','https://api.dicebear.com/9.x/shapes/png?seed=HOOD',51,1),
('stocks','ADBEON/USDT','ADBEON','USDT','ADBE','ADBE','https://api.dicebear.com/9.x/shapes/png?seed=ADBE',52,1),
('stocks','MRVLON/USDT','MRVLON','USDT','MRVL','MRVL','https://api.dicebear.com/9.x/shapes/png?seed=MRVL',53,1),
('stocks','AMCON/USDT','AMCON','USDT','AMC','AMC','https://api.dicebear.com/9.x/shapes/png?seed=AMC',54,1),
('stocks','COINON/USDT','COINON','USDT','COIN','COIN','https://api.dicebear.com/9.x/shapes/png?seed=COIN',55,1),
('stocks','APOON/USDT','APOON','USDT','APO','APO','https://api.dicebear.com/9.x/shapes/png?seed=APO',56,1),
('stocks','APPON/USDT','APPON','USDT','APP','APP','https://api.dicebear.com/9.x/shapes/png?seed=APP',57,1),
('stocks','AVGOON/USDT','AVGOON','USDT','AVGO','AVGO','https://api.dicebear.com/9.x/shapes/png?seed=AVGO',58,1),
('stocks','AXPON/USDT','AXPON','USDT','AXP','AXP','https://api.dicebear.com/9.x/shapes/png?seed=AXP',59,1),
('stocks','BACON/USDT','BACON','USDT','BAC','BAC','https://api.dicebear.com/9.x/shapes/png?seed=BAC',60,1),
('stocks','BAON/USDT','BAON','USDT','BA','BA','https://api.dicebear.com/9.x/shapes/png?seed=BA',61,1),
('stocks','BIDUON/USDT','BIDUON','USDT','BIDU','BIDU','https://api.dicebear.com/9.x/shapes/png?seed=BIDU',62,1),
('stocks','UNOON/USDT','UNOON','USDT','UNO','UNO','https://api.dicebear.com/9.x/shapes/png?seed=UNO',63,1),
('stocks','BTGON/USDT','BTGON','USDT','BTG','BTG','https://api.dicebear.com/9.x/shapes/png?seed=BTG',64,1),
('stocks','CIFRON/USDT','CIFRON','USDT','CIFR','CIFR','https://api.dicebear.com/9.x/shapes/png?seed=CIFR',65,1),
('stocks','CON/USDT','CON','USDT','C','C','https://api.dicebear.com/9.x/shapes/png?seed=C',66,1),
('stocks','COPON/USDT','COPON','USDT','COP','COP','https://api.dicebear.com/9.x/shapes/png?seed=COP',67,1),
('stocks','COPXON/USDT','COPXON','USDT','COPX','COPX','https://api.dicebear.com/9.x/shapes/png?seed=COPX',68,1),
('stocks','CRCLON/USDT','CRCLON','USDT','CRCL','CRCL','https://api.dicebear.com/9.x/shapes/png?seed=CRCL',69,1),
('stocks','CRMON/USDT','CRMON','USDT','CRM','CRM','https://api.dicebear.com/9.x/shapes/png?seed=CRM',70,1),
('stocks','CSCOON/USDT','CSCOON','USDT','CSCO','CSCO','https://api.dicebear.com/9.x/shapes/png?seed=CSCO',71,1),
('stocks','CVXON/USDT','CVXON','USDT','CVX','CVX','https://api.dicebear.com/9.x/shapes/png?seed=CVX',72,1),
('stocks','DASHON/USDT','DASHON','USDT','DASH','DASH','https://api.dicebear.com/9.x/shapes/png?seed=DASH',73,1),
('stocks','DISON/USDT','DISON','USDT','DIS','DIS','https://api.dicebear.com/9.x/shapes/png?seed=DIS',74,1),
('stocks','DNNON/USDT','DNNON','USDT','DNN','DNN','https://api.dicebear.com/9.x/shapes/png?seed=DNN',75,1),
('stocks','EQIXON/USDT','EQIXON','USDT','EQIX','EQIX','https://api.dicebear.com/9.x/shapes/png?seed=EQIX',76,1),
('stocks','FIGON/USDT','FIGON','USDT','FIG','FIG','https://api.dicebear.com/9.x/shapes/png?seed=FIG',77,1),
('stocks','FSOLON/USDT','FSOLON','USDT','FSOL','FSOL','https://api.dicebear.com/9.x/shapes/png?seed=FSOL',78,1),
('stocks','GMEON/USDT','GMEON','USDT','GME','GME','https://api.dicebear.com/9.x/shapes/png?seed=GME',79,1),
('stocks','GRABON/USDT','GRABON','USDT','GRAB','GRAB','https://api.dicebear.com/9.x/shapes/png?seed=GRAB',80,1),
('stocks','IRENON/USDT','IRENON','USDT','IREN','IREN','https://api.dicebear.com/9.x/shapes/png?seed=IREN',81,1),
('stocks','JDON/USDT','JDON','USDT','JD','JD','https://api.dicebear.com/9.x/shapes/png?seed=JD',82,1),
('crypto','BNB/USDT','BNB','USDT','BNB','BNB','https://api.dicebear.com/9.x/shapes/png?seed=BNB',83,1),
('crypto','WBTC/USDT','WBTC','USDT','WBTC','WBTC','https://api.dicebear.com/9.x/shapes/png?seed=WBTC',84,1),
('crypto','WBETH/USDT','WBETH','USDT','WBETH','WBETH','https://api.dicebear.com/9.x/shapes/png?seed=WBETH',85,1),
('crypto','SOL/USDT','SOL','USDT','SOL','SOL','https://api.dicebear.com/9.x/shapes/png?seed=SOL',86,1),
('crypto','XRP/USDT','XRP','USDT','XRP','XRP','https://api.dicebear.com/9.x/shapes/png?seed=XRP',87,1),
('crypto','LINK/USDT','LINK','USDT','LINK','LINK','https://api.dicebear.com/9.x/shapes/png?seed=LINK',88,1),
('crypto','DOGE/USDT','DOGE','USDT','DOGE','DOGE','https://api.dicebear.com/9.x/shapes/png?seed=DOGE',89,1),
('crypto','TON/USDT','TON','USDT','TON','TON','https://api.dicebear.com/9.x/shapes/png?seed=TON',90,1),
('crypto','UNI/USDT','UNI','USDT','UNI','UNI','https://api.dicebear.com/9.x/shapes/png?seed=UNI',91,1),
('crypto','AAVE/USDT','AAVE','USDT','AAVE','AAVE','https://api.dicebear.com/9.x/shapes/png?seed=AAVE',92,1),
('crypto','ASTER/USDT','ASTER','USDT','ASTER','ASTER','https://api.dicebear.com/9.x/shapes/png?seed=ASTER',93,1),
('crypto','CAKE/USDT','CAKE','USDT','CAKE','CAKE','https://api.dicebear.com/9.x/shapes/png?seed=CAKE',94,1),
('crypto','TWT/USDT','TWT','USDT','TWT','TWT','https://api.dicebear.com/9.x/shapes/png?seed=TWT',95,1),
('crypto','BCH/USDT','BCH','USDT','BCH','BCH','https://api.dicebear.com/9.x/shapes/png?seed=BCH',96,1),
('crypto','1INCH/USDT','1INCH','USDT','1INCH','1INCH','https://api.dicebear.com/9.x/shapes/png?seed=1INCH',97,1),
('crypto','SHIB/USDT','SHIB','USDT','SHIB','SHIB','https://api.dicebear.com/9.x/shapes/png?seed=SHIB',98,1),
('crypto','ZEC/USDT','ZEC','USDT','ZEC','ZEC','https://api.dicebear.com/9.x/shapes/png?seed=ZEC',99,1),
('crypto','LTC/USDT','LTC','USDT','LTC','LTC','https://api.dicebear.com/9.x/shapes/png?seed=LTC',100,1),
('crypto','WLFI/USDT','WLFI','USDT','WLFI','WLFI','https://api.dicebear.com/9.x/shapes/png?seed=WLFI',101,1),
('crypto','DOT/USDT','DOT','USDT','DOT','DOT','https://api.dicebear.com/9.x/shapes/png?seed=DOT',102,1),
('crypto','PEPE/USDT','PEPE','USDT','PEPE','PEPE','https://api.dicebear.com/9.x/shapes/png?seed=PEPE',103,1),
('crypto','ATOM/USDT','ATOM','USDT','ATOM','ATOM','https://api.dicebear.com/9.x/shapes/png?seed=ATOM',104,1),
('crypto','PENGU/USDT','PENGU','USDT','PENGU','PENGU','https://api.dicebear.com/9.x/shapes/png?seed=PENGU',105,1),
('crypto','FOLKI/USDT','FOLKI','USDT','FOLKI','FOLKI','https://api.dicebear.com/9.x/shapes/png?seed=FOLKI',106,1)
ON DUPLICATE KEY UPDATE base_asset=VALUES(base_asset), quote_asset=VALUES(quote_asset), token_symbol=VALUES(token_symbol), display_name=VALUES(display_name), logo_url=VALUES(logo_url), sort_order=VALUES(sort_order), active=VALUES(active), updated_at=CURRENT_TIMESTAMP;
